# version: "3"
# services:
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: pass123


version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5435:5432
    environment:
            # POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 'pass123'
            # POSTGRES_DB: ilovecoffe